/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
    return (
        <div id={"examples"} className="bg-gray-50">
            <div className="max-w-4xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
                <div className="text-center">
                    <h2 className="text-base font-semibold text-teal-600 tracking-wide uppercase">Examples</h2>
                    <p className="mt-1 text-3xl font-extrabold text-gray-900 sm:text-4xl sm:tracking-tight lg:text-5xl">
                        4,928 decks generated by 1,298 happy customers
                    </p>
                    <p className="max-w-xl mt-5 mx-auto text-base text-gray-500">
                        Discover why our customers love our deck generator.
                    </p>
                </div>
            </div>
        </div>
    )
}